stages:
  - prepare
  - test

default:
  before_script:
    - ls -hal
    - hostname
    - whoami
    - echo "PATH:"
    - echo $PATH | tr ":" "\n"
    - echo "SHELL = $SHELL"
    # Source conda
    - source /home/gitlab-runner/miniconda3/etc/profile.d/conda.sh
    - which conda

install-dependencies:
  tags:
    - pipeline
  stage: prepare
  script:
    # Be sure we have a python3.7, install it with conda
    - conda create -n m74-tests python==3.7 --yes
    - conda activate m74-tests
    # Install poetry
    - pip install poetry
    - poetry --version
    - poetry env info
    # Install the dependencies of the tests
    - poetry install -vv
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

run-tests:
  tags:
    - pipeline
  stage: test
  script:
    - conda activate m74-tests
    - ./run_tests.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
