stages:
  - test

run-tests:
  tags:
    - pipeline
  stage: test
  script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - source $HOME/.poetry/env
    - poetry --version
    - poetry env info
    - poetry install -vv
    - ./run_tests.sh
  only:
    - merge_requests
