[sequence]
patterns = [
    "[a-z]{2}[0-9]{3}",
    "previz[0-9]{3}"
]
description =  """
(Two lowercase letters OR the string 'previz') \
followed by three numbers. \
EG: sc010 OR previz010\
"""

[shot]
appends_to = "sequence"
appends_with = "_"
patterns = [ "[0-9]{4}" ]
description = "Four digits. EG: 0010"